# Generated by Django 4.2.6 on 2024-09-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_alter_profile_privacysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='privacysettings',
        ),
    ]
