# Generated by Django 4.2.6 on 2024-09-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_remove_profile_privacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='publicaccount',
            field=models.BooleanField(default=True),
        ),
    ]
