# Generated by Django 4.2.6 on 2024-09-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_profile_publicaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivacySettings',
        ),
    ]
