# Generated by Django 4.2.6 on 2024-09-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_delete_privacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(default='images/profilepictures/unknown-user.png', upload_to='images/profilepictures/'),
        ),
    ]
