# Generated by Django 4.2.6 on 2024-12-01 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0013_notifierjunctiontable'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofiles.notifierjunctiontable'),
            preserve_default=False,
        ),
    ]
