# Generated by Django 4.2.6 on 2024-12-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0018_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(default='images/unknown-user.png', upload_to='images/'),
        ),
    ]
